using System.Collections.Generic;
using UnityEngine;

// PORT: PC input converted into the original game's gestures (Android: swipe and tap).
//
// Run actions (lanes, jump, slide, shoot, pause, score, lights, missions) use the keys and gamepad buttons
// set in the settings menu (PortBindings, PortControlsMenu). Defaults: keyboard arrows, Space/Ctrl shoot,
// Esc pauses, S/L/Q say score/lights/missions; see PortBindings for the gamepads.
// The sticks and the d-pad always act as arrows, in menus and during the run.
// Esc = pause gesture (two-finger double tap): pauses the game or skips the tutorial.
// PORT: in menus Esc goes back to the previous screen (GameState.PortBack); in the pause menu it resumes the game.
// In menus the accessibility plugin uses arrows, Enter and Esc (UAP default on Windows).
//
// Gamepad (Xbox/XInput and PlayStation DualShock 4/DualSense, detected by name):
//   In menus: Cross/Options/touchpad (A/Start) = Enter; Circle/Share (B/Back) = Esc.
//   In the pause menu and the tutorial skip confirmation: the pause buttons resume, like Esc.
// "During the run" = PlayGame state with the accessibility plugin paused (no menu shown).
// PlayStation gamepads are read directly through HID when possible (PortSonyInput): this also
// works over Bluetooth, where Windows does not deliver the buttons to Unity.
// Gamepad rumble: see PortRumble.
//
// Mouse: drag with the left button = swipe; click without dragging = tap.
//
// The values are only valid during the frame in which the gesture happened.
[DefaultExecutionOrder(-1000)]
public class PortInput : MonoBehaviour
{
	public static bool GameSwipeLeft { get; private set; }

	public static bool GameSwipeRight { get; private set; }

	public static bool GameSwipeUp { get; private set; }

	public static bool GameSwipeDown { get; private set; }

	public static bool GameTap { get; private set; }

	// Virtual keys generated by the gamepad this frame
	private static bool s_Up;

	private static bool s_Down;

	private static bool s_Left;

	private static bool s_Right;

	private static bool s_Submit;

	private static bool s_Cancel;

	private static bool s_PauseToggle;

	private const float c_StickThreshold = 0.6f;

	private const float c_StickRelease = 0.3f;

	// Same threshold as the original game to recognize a swipe (2% of the screen width)
	private const float c_MouseSwipeThreshold = 0.02f;

	private Vector2 m_StickLast;

	private bool m_MouseDown;

	private bool m_MouseSwiped;

	private Vector2 m_MouseStart;

	[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
	private static void Create()
	{
		GameObject go = new GameObject("PortInput");
		DontDestroyOnLoad(go);
		go.AddComponent<PortInput>();
	}

	// Controls menu: while true, the next key or gamepad button is reported in CapturedKey/CapturedPad
	// (for one frame) and no other input reaches the game or the accessibility plugin.
	public static bool Capturing { get; set; }

	public static int CapturedKey { get; private set; } = -1;

	public static int CapturedPad { get; private set; } = -1;

	// The connected gamepad's layout in PortBindings (PlayStation or Xbox)
	public static int PadDevice => SonyGamepad ? PortBindings.PlayStation : PortBindings.Xbox;

	// Replaces Input.GetKeyDown where the game/UAP reads keys: includes the gamepad.
	public static bool GetKeyDown(KeyCode key)
	{
		if (Capturing)
		{
			return false;
		}
		if (Input.GetKeyDown(key))
		{
			return true;
		}
		switch (key)
		{
		case KeyCode.UpArrow:
			return s_Up;
		case KeyCode.DownArrow:
			return s_Down;
		case KeyCode.LeftArrow:
			return s_Left;
		case KeyCode.RightArrow:
			return s_Right;
		case KeyCode.Return:
			return s_Submit;
		case KeyCode.Escape:
			return s_Cancel;
		default:
			return false;
		}
	}

	private static float ReadAxis(string axis)
	{
		try
		{
			return Input.GetAxisRaw(axis);
		}
		catch (System.ArgumentException)
		{
			return 0f;
		}
	}

	private const float c_SteamEchoWindow = 0.3f;

	private float m_LastPadEscTime = -10f;

	private static bool IsPauseMenu()
	{
		CustomGameManager cgm = CustomGameManager.Instance;
		GameState top = (cgm != null) ? cgm.topState : null;
		if (top == null)
		{
			return false;
		}
		// The tutorial's skip confirmation is its pause menu: Start/Options resume the tutorial, like Esc
		return top.GetName() == GameStateName.Pause || (top.GetName() == GameStateName.PlayGame && top.GetStatus() == GameStateStatus.TutorialPaused);
	}

	private static bool TryBack()
	{
		// Controls menu (settings): Esc goes back one page
		if (PortControlsMenu.IsOpen)
		{
			PortControlsMenu.Back();
			return true;
		}
		// Update dialog shown after the logo: Esc = No
		if (PortUpdater.DialogOpen)
		{
			PortUpdater.Decline();
			return true;
		}
		// Editing a field: Esc only cancels the edit (handled by the accessibility plugin)
		if (UAP_AccessibilityManager.PortIsInteracting())
		{
			return true;
		}
		CustomGameManager cgm = CustomGameManager.Instance;
		GameState top = (cgm != null) ? cgm.topState : null;
		return top != null && top.PortBack();
	}

	private void OnApplicationQuit()
	{
		PortSonyInput.Shutdown();
	}

	private void Update()
	{
		GameSwipeLeft = false;
		GameSwipeRight = false;
		GameSwipeUp = false;
		GameSwipeDown = false;
		GameTap = false;
		s_Up = false;
		s_Down = false;
		s_Left = false;
		s_Right = false;
		s_Submit = false;
		s_Cancel = false;
		s_PauseToggle = false;
		CapturedKey = -1;
		CapturedPad = -1;
		if (Capturing)
		{
			UpdateCapture();
			return;
		}
		UpdateJoystick();
		UpdateMouse();
		// Esc from keyboard or gamepad: in menus goes back to the previous screen; otherwise pause gesture.
		// Steam (desktop configuration) also turns gamepad buttons into keys: the same press
		// arrived as a button and, a moment later, as a keyboard Esc, pausing again.
		// So a keyboard Esc right after a gamepad pause/back button is ignored.
		// During the run the keyboard pause keys are the ones set in the controls menu (Esc by default)
		bool keyboardEsc = IsRunning() ? KeyDown(PortBindings.Get(PortBindings.Keyboard, PortAction.Pause)) : Input.GetKeyDown(KeyCode.Escape);
		if (keyboardEsc && Time.unscaledTime - m_LastPadEscTime < c_SteamEchoWindow)
		{
			Debug.Log("[PortInput] Keyboard Esc ignored (gamepad echo)");
			keyboardEsc = false;
		}
		if (s_Cancel || s_PauseToggle)
		{
			m_LastPadEscTime = Time.unscaledTime;
		}
		bool esc = keyboardEsc || s_Cancel;
		if (esc || s_PauseToggle)
		{
			if (!(esc && !IsRunning() && TryBack()))
			{
				UAP_AccessibilityManager.PortTriggerPauseToggle();
			}
		}
	}

	// Button numbering in Unity (legacy Input Manager).
	// Xbox: 0 A, 1 B, 2 X, 3 Y, 4 LB, 5 RB, 6 Back, 7 Start, 8/9 stick clicks (LT/RT are axes 9 and 10).
	// PlayStation: 0 Square, 1 Cross, 2 Circle, 3 Triangle, 4 L1, 5 R1, 6 L2, 7 R2, 8 Share, 9 Options,
	// 10 L3, 11 R3, 12 PS, 13 Touchpad.
	// Menu buttons are fixed; the run buttons come from PortBindings.
	private static readonly int[] c_XboxSubmit = { 0, 7 };

	private static readonly int[] c_XboxCancel = { 1, 6 };

	private static readonly int[] c_SonySubmit = { 1, 9, 13 };

	private static readonly int[] c_SonyCancel = { 2, 8 };

	private bool m_LeftTriggerDown;

	private bool m_RightTriggerDown;

	// Xbox trigger presses this frame (PortBindings.c_LT / c_RT)
	private static bool s_LeftTrigger;

	private static bool s_RightTrigger;

	private static string s_LastJoystickName;

	private static bool s_Sony;

	private static bool s_Connected;

	private static float s_NextNameCheck = -1f;

	// A gamepad is connected: on-screen/spoken instructions name its buttons instead of keys.
	public static bool GamepadConnected
	{
		get
		{
			DetectControllerType();
			return s_Connected || PortSonyInput.Active;
		}
	}

	// The connected gamepad uses the PlayStation layout (Cross, Circle, Options...)
	public static bool SonyGamepad
	{
		get
		{
			DetectControllerType();
			return s_Sony || PortSonyInput.Active;
		}
	}

	// DualShock 4 and DualSense without an emulator show up as "Wireless Controller" (DirectInput);
	// any other gamepad uses the Xbox layout (XInput), including DS4Windows/Steam.
	private static void DetectControllerType()
	{
		if (s_NextNameCheck >= 0f && Time.unscaledTime < s_NextNameCheck)
		{
			return;
		}
		s_NextNameCheck = Time.unscaledTime + 2f;
		s_Sony = false;
		s_Connected = false;
		foreach (string name in Input.GetJoystickNames())
		{
			if (string.IsNullOrEmpty(name))
			{
				continue;
			}
			if (name != s_LastJoystickName)
			{
				s_LastJoystickName = name;
				Debug.Log("[PortInput] Gamepad: " + name);
			}
			string n = name.ToLowerInvariant();
			s_Sony = !n.Contains("xbox") && !n.Contains("xinput") && (n.Contains("wireless controller") || n.Contains("dualsense") || n.Contains("dualshock") || n.Contains("sony") || n.Contains("playstation"));
			s_Connected = true;
			break;
		}
	}

	// Run in progress: the game is in PlayGame and the accessibility plugin is paused (no menu shown).
	private static bool IsRunning()
	{
		CustomGameManager cgm = CustomGameManager.Instance;
		GameState top = (cgm != null) ? cgm.topState : null;
		if (top == null || top.GetName() != GameStateName.PlayGame)
		{
			return false;
		}
		return !UAP_AccessibilityManager.IsEnabled() || !UAP_AccessibilityManager.IsActive();
	}

	// true = PlayStation gamepad read directly through HID (PortSonyInput); Unity input is ignored for it.
	private static bool s_UseHid;

	private static bool PadDown(int code)
	{
		if (code == PortBindings.c_LT)
		{
			return s_LeftTrigger;
		}
		if (code == PortBindings.c_RT)
		{
			return s_RightTrigger;
		}
		if (code < 0 || code > 19)
		{
			return false;
		}
		return s_UseHid ? PortSonyInput.WasPressed(code) : Input.GetKeyDown(KeyCode.JoystickButton0 + code);
	}

	private static bool PadDown(IList<int> codes)
	{
		foreach (int code in codes)
		{
			if (PadDown(code))
			{
				return true;
			}
		}
		return false;
	}

	private static bool KeyDown(IList<int> codes)
	{
		foreach (int code in codes)
		{
			if (Input.GetKeyDown((KeyCode)code))
			{
				return true;
			}
		}
		return false;
	}

	// Run action pressed on the keyboard or on the connected gamepad
	private static bool ActionDown(PortAction action)
	{
		return KeyDown(PortBindings.Get(PortBindings.Keyboard, action)) || PadDown(PortBindings.Get(s_Sony ? PortBindings.PlayStation : PortBindings.Xbox, action));
	}

	private static KeyCode[] s_KeyboardKeys;

	// Controls menu: reports the first keyboard key or gamepad button pressed this frame
	private void UpdateCapture()
	{
		ReadPad();
		if (s_KeyboardKeys == null)
		{
			List<KeyCode> keys = new List<KeyCode>();
			foreach (KeyCode key in System.Enum.GetValues(typeof(KeyCode)))
			{
				if (key > KeyCode.None && key < KeyCode.Mouse0 && !keys.Contains(key))
				{
					keys.Add(key);
				}
			}
			s_KeyboardKeys = keys.ToArray();
		}
		foreach (KeyCode key in s_KeyboardKeys)
		{
			if (Input.GetKeyDown(key))
			{
				CapturedKey = (int)key;
				return;
			}
		}
		for (int i = 0; i < 20; i++)
		{
			if (PadDown(i))
			{
				CapturedPad = i;
				return;
			}
		}
		if (s_LeftTrigger)
		{
			CapturedPad = PortBindings.c_LT;
		}
		else if (s_RightTrigger)
		{
			CapturedPad = PortBindings.c_RT;
		}
	}

	private static Vector2 Strongest(Vector2 a, Vector2 b)
	{
		return (b.sqrMagnitude > a.sqrMagnitude) ? b : a;
	}

	// Gamepad state for this frame: layout, HID, stick/d-pad directions (s_Up...) and trigger presses
	private void ReadPad()
	{
		DetectControllerType();
		PortSonyInput.Poll();
		s_UseHid = PortSonyInput.Active;
		if (s_UseHid)
		{
			s_Sony = true;
		}
		// Unity: stick Y is positive downwards (PortJoyY is already inverted); d-pad Y is positive upwards.
		Vector2 value = new Vector2(ReadAxis("PortJoyX"), ReadAxis("PortJoyY"));
		if (s_UseHid)
		{
			value = Strongest(Strongest(PortSonyInput.LeftStick, PortSonyInput.RightStick), PortSonyInput.Dpad);
		}
		else if (s_Sony)
		{
			value = Strongest(value, new Vector2(ReadAxis("PortAxis2"), -ReadAxis("PortAxis5")));
			value = Strongest(value, new Vector2(ReadAxis("PortAxis6"), ReadAxis("PortAxis7")));
		}
		else
		{
			value = Strongest(value, new Vector2(ReadAxis("PortAxis3"), -ReadAxis("PortAxis4")));
			value = Strongest(value, new Vector2(ReadAxis("PortAxis5"), ReadAxis("PortAxis6")));
		}
		// Generates a key "press" only when the direction crosses the threshold (no repeat while held)
		if (Mathf.Abs(m_StickLast.x) < c_StickRelease && Mathf.Abs(m_StickLast.y) < c_StickRelease)
		{
			if (Mathf.Abs(value.x) >= c_StickThreshold || Mathf.Abs(value.y) >= c_StickThreshold)
			{
				if (Mathf.Abs(value.x) > Mathf.Abs(value.y))
				{
					if (value.x < 0f)
					{
						s_Left = true;
					}
					else
					{
						s_Right = true;
					}
				}
				else if (value.y > 0f)
				{
					s_Up = true;
				}
				else
				{
					s_Down = true;
				}
				m_StickLast = value;
			}
		}
		else if (Mathf.Abs(value.x) < c_StickRelease && Mathf.Abs(value.y) < c_StickRelease)
		{
			m_StickLast = Vector2.zero;
		}
		// Xbox triggers are axes: generate a press when they pass the halfway point
		s_LeftTrigger = false;
		s_RightTrigger = false;
		if (!s_Sony)
		{
			bool lt = ReadAxis("PortAxis8") > 0.5f;
			bool rt = ReadAxis("PortAxis9") > 0.5f;
			s_LeftTrigger = lt && !m_LeftTriggerDown;
			s_RightTrigger = rt && !m_RightTriggerDown;
			m_LeftTriggerDown = lt;
			m_RightTriggerDown = rt;
		}
	}

	private void UpdateJoystick()
	{
		ReadPad();
		if (IsRunning())
		{
			// Run: the keys and buttons set for each action (PortBindings) and the sticks/d-pad become the
			// game gestures. The keyboard pause keys are handled in Update (Steam echo filter).
			GameSwipeLeft |= s_Left || ActionDown(PortAction.Left);
			GameSwipeRight |= s_Right || ActionDown(PortAction.Right);
			GameSwipeUp |= s_Up || ActionDown(PortAction.Jump);
			GameSwipeDown |= s_Down || ActionDown(PortAction.Slide);
			GameTap |= ActionDown(PortAction.Shoot);
			if (PadDown(PortBindings.Get(s_Sony ? PortBindings.PlayStation : PortBindings.Xbox, PortAction.Pause)))
			{
				s_PauseToggle = true;
			}
			if (ActionDown(PortAction.Score))
			{
				PortStatus.SayScore();
			}
			if (ActionDown(PortAction.Lights))
			{
				PortStatus.SayLights();
			}
			if (ActionDown(PortAction.Missions))
			{
				PortStatus.SayMissions();
			}
			return;
		}
		// Pause menu or tutorial skip confirmation: the pause buttons and keys resume, like Esc
		int device = s_Sony ? PortBindings.PlayStation : PortBindings.Xbox;
		if (IsPauseMenu() && (PadDown(PortBindings.Get(device, PortAction.Pause)) || (KeyDown(PortBindings.Get(PortBindings.Keyboard, PortAction.Pause)) && !Input.GetKeyDown(KeyCode.Escape))))
		{
			s_Cancel = true;
			return;
		}
		if (PadDown(s_Sony ? c_SonySubmit : c_XboxSubmit))
		{
			s_Submit = true;
		}
		if (PadDown(s_Sony ? c_SonyCancel : c_XboxCancel))
		{
			s_Cancel = true;
		}
	}

	private void UpdateMouse()
	{
		if (Input.touchCount > 0)
		{
			return;
		}
		if (Input.GetMouseButtonDown(0))
		{
			m_MouseDown = true;
			m_MouseSwiped = false;
			m_MouseStart = Input.mousePosition;
		}
		else if (m_MouseDown && Input.GetMouseButton(0) && !m_MouseSwiped)
		{
			Vector2 diff = (Vector2)Input.mousePosition - m_MouseStart;
			diff = new Vector2(diff.x / (float)Screen.width, diff.y / (float)Screen.width);
			if (diff.magnitude > c_MouseSwipeThreshold)
			{
				if (Mathf.Abs(diff.y) <= Mathf.Abs(diff.x))
				{
					if (diff.x < 0f)
					{
						GameSwipeLeft = true;
					}
					else
					{
						GameSwipeRight = true;
					}
				}
				else if (diff.y < 0f)
				{
					GameSwipeDown = true;
				}
				else
				{
					GameSwipeUp = true;
				}
				m_MouseSwiped = true;
			}
		}
		if (Input.GetMouseButtonUp(0) && m_MouseDown)
		{
			m_MouseDown = false;
			if (!m_MouseSwiped)
			{
				GameTap = true;
			}
		}
	}
}
