using UnityEngine;

// PORT: PC input converted into the original game's gestures (Android: swipe and tap).
//
// Keyboard (already in the original code): arrows = swipe, Space = tap (shoot).
// Esc = pause gesture (two-finger double tap): pauses the game or skips the tutorial.
// PORT: in menus Esc goes back to the previous screen (GameState.PortBack); in the pause menu it resumes the game.
// In menus the accessibility plugin uses arrows, Enter and Esc (UAP default on Windows).
//
// Gamepad (Xbox/XInput and PlayStation DualShock 4/DualSense, detected by name):
//   sticks and d-pad = arrows (menus and run);
//   During the run: Cross (A) jumps, Circle (B) slides, Triangle/Square/touchpad (X/Y) shoot,
//     L1/L2 (LB/LT) = left lane, R1/R2 (RB/RT) = right lane, Options/Share (Start/Back) pause.
//   In menus: Cross/Options/touchpad (A/Start) = Enter; Circle/Share (B/Back) = Esc.
//   In the pause menu: Options/Share (Start/Back) resume the game, like Esc.
// "During the run" = PlayGame state with the accessibility plugin paused (no menu shown).
// PlayStation gamepads are read directly through HID when possible (PortSonyInput): this also
// works over Bluetooth, where Windows does not deliver the buttons to Unity.
// Gamepad rumble: see PortRumble.
//
// Mouse: drag with the left button = swipe; click without dragging = tap.
//
// The values are only valid during the frame in which the gesture happened.
[DefaultExecutionOrder(-1000)]
public class PortInput : MonoBehaviour
{
	public static bool GameSwipeLeft { get; private set; }

	public static bool GameSwipeRight { get; private set; }

	public static bool GameSwipeUp { get; private set; }

	public static bool GameSwipeDown { get; private set; }

	public static bool GameTap { get; private set; }

	// Virtual keys generated by the gamepad this frame
	private static bool s_Up;

	private static bool s_Down;

	private static bool s_Left;

	private static bool s_Right;

	private static bool s_Submit;

	private static bool s_Cancel;

	private static bool s_PauseToggle;

	private const float c_StickThreshold = 0.6f;

	private const float c_StickRelease = 0.3f;

	// Same threshold as the original game to recognize a swipe (2% of the screen width)
	private const float c_MouseSwipeThreshold = 0.02f;

	private Vector2 m_StickLast;

	private bool m_MouseDown;

	private bool m_MouseSwiped;

	private Vector2 m_MouseStart;

	[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
	private static void Create()
	{
		GameObject go = new GameObject("PortInput");
		DontDestroyOnLoad(go);
		go.AddComponent<PortInput>();
	}

	// Replaces Input.GetKeyDown where the game/UAP reads keys: includes the gamepad.
	public static bool GetKeyDown(KeyCode key)
	{
		if (Input.GetKeyDown(key))
		{
			return true;
		}
		switch (key)
		{
		case KeyCode.UpArrow:
			return s_Up;
		case KeyCode.DownArrow:
			return s_Down;
		case KeyCode.LeftArrow:
			return s_Left;
		case KeyCode.RightArrow:
			return s_Right;
		case KeyCode.Return:
			return s_Submit;
		case KeyCode.Escape:
			return s_Cancel;
		default:
			return false;
		}
	}

	private static float ReadAxis(string axis)
	{
		try
		{
			return Input.GetAxisRaw(axis);
		}
		catch (System.ArgumentException)
		{
			return 0f;
		}
	}

	private const float c_SteamEchoWindow = 0.3f;

	private float m_LastPadEscTime = -10f;

	private static bool IsPauseMenu()
	{
		CustomGameManager cgm = CustomGameManager.Instance;
		GameState top = (cgm != null) ? cgm.topState : null;
		return top != null && top.GetName() == GameStateName.Pause;
	}

	private static bool TryBack()
	{
		// Editing a field: Esc only cancels the edit (handled by the accessibility plugin)
		if (UAP_AccessibilityManager.PortIsInteracting())
		{
			return true;
		}
		CustomGameManager cgm = CustomGameManager.Instance;
		GameState top = (cgm != null) ? cgm.topState : null;
		return top != null && top.PortBack();
	}

	private void OnApplicationQuit()
	{
		PortSonyInput.Shutdown();
	}

	private void Update()
	{
		GameSwipeLeft = false;
		GameSwipeRight = false;
		GameSwipeUp = false;
		GameSwipeDown = false;
		GameTap = false;
		s_Up = false;
		s_Down = false;
		s_Left = false;
		s_Right = false;
		s_Submit = false;
		s_Cancel = false;
		s_PauseToggle = false;
		UpdateJoystick();
		UpdateMouse();
		// Esc from keyboard or gamepad: in menus goes back to the previous screen; otherwise pause gesture.
		// Steam (desktop configuration) also turns gamepad buttons into keys: the same press
		// arrived as a button and, a moment later, as a keyboard Esc, pausing again.
		// So a keyboard Esc right after a gamepad pause/back button is ignored.
		bool keyboardEsc = Input.GetKeyDown(KeyCode.Escape);
		if (keyboardEsc && Time.unscaledTime - m_LastPadEscTime < c_SteamEchoWindow)
		{
			Debug.Log("[PortInput] Keyboard Esc ignored (gamepad echo)");
			keyboardEsc = false;
		}
		if (s_Cancel || s_PauseToggle)
		{
			m_LastPadEscTime = Time.unscaledTime;
		}
		bool esc = keyboardEsc || s_Cancel;
		if (esc || s_PauseToggle)
		{
			if (!(esc && !IsRunning() && TryBack()))
			{
				UAP_AccessibilityManager.PortTriggerPauseToggle();
			}
		}
	}

	// Button numbering in Unity (legacy Input Manager).
	// Xbox: 0 A, 1 B, 2 X, 3 Y, 4 LB, 5 RB, 6 Back, 7 Start (LT/RT are axes 9 and 10).
	// PlayStation: 0 Square, 1 Cross, 2 Circle, 3 Triangle, 4 L1, 5 R1, 6 L2, 7 R2, 8 Share, 9 Options, 13 Touchpad.
	private class Layout
	{
		public KeyCode[] Jump;      // run: jump (= d-pad up)

		public KeyCode[] Slide;     // run: slide (= d-pad down)

		public KeyCode[] Shoot;     // run: shoot (= Space)

		public KeyCode[] Left;      // run: left lane

		public KeyCode[] Right;     // run: right lane

		public KeyCode[] Pause;     // run: pause (= Esc)

		public KeyCode[] Submit;    // menus: Enter

		public KeyCode[] Cancel;    // menus: Esc
	}

	private static readonly Layout c_Xbox = new Layout
	{
		Jump = new[] { KeyCode.JoystickButton0 },
		Slide = new[] { KeyCode.JoystickButton1 },
		Shoot = new[] { KeyCode.JoystickButton2, KeyCode.JoystickButton3 },
		Left = new[] { KeyCode.JoystickButton4 },
		Right = new[] { KeyCode.JoystickButton5 },
		Pause = new[] { KeyCode.JoystickButton6, KeyCode.JoystickButton7 },
		Submit = new[] { KeyCode.JoystickButton0, KeyCode.JoystickButton7 },
		Cancel = new[] { KeyCode.JoystickButton1, KeyCode.JoystickButton6 }
	};

	private static readonly Layout c_Sony = new Layout
	{
		Jump = new[] { KeyCode.JoystickButton1 },
		Slide = new[] { KeyCode.JoystickButton2 },
		Shoot = new[] { KeyCode.JoystickButton0, KeyCode.JoystickButton3, KeyCode.JoystickButton13 },
		Left = new[] { KeyCode.JoystickButton4, KeyCode.JoystickButton6 },
		Right = new[] { KeyCode.JoystickButton5, KeyCode.JoystickButton7 },
		Pause = new[] { KeyCode.JoystickButton8, KeyCode.JoystickButton9 },
		Submit = new[] { KeyCode.JoystickButton1, KeyCode.JoystickButton9, KeyCode.JoystickButton13 },
		Cancel = new[] { KeyCode.JoystickButton2, KeyCode.JoystickButton8 }
	};

	private bool m_LeftTriggerDown;

	private bool m_RightTriggerDown;

	private string m_LastJoystickName;

	private bool m_Sony;

	private float m_NextNameCheck;

	// DualShock 4 and DualSense without an emulator show up as "Wireless Controller" (DirectInput);
	// any other gamepad uses the Xbox layout (XInput), including DS4Windows/Steam.
	private void DetectControllerType()
	{
		if (Time.unscaledTime < m_NextNameCheck)
		{
			return;
		}
		m_NextNameCheck = Time.unscaledTime + 2f;
		m_Sony = false;
		foreach (string name in Input.GetJoystickNames())
		{
			if (string.IsNullOrEmpty(name))
			{
				continue;
			}
			if (name != m_LastJoystickName)
			{
				m_LastJoystickName = name;
				Debug.Log("[PortInput] Gamepad: " + name);
			}
			string n = name.ToLowerInvariant();
			m_Sony = !n.Contains("xbox") && !n.Contains("xinput") && (n.Contains("wireless controller") || n.Contains("dualsense") || n.Contains("dualshock") || n.Contains("sony") || n.Contains("playstation"));
			break;
		}
	}

	// Run in progress: the game is in PlayGame and the accessibility plugin is paused (no menu shown).
	private static bool IsRunning()
	{
		CustomGameManager cgm = CustomGameManager.Instance;
		GameState top = (cgm != null) ? cgm.topState : null;
		if (top == null || top.GetName() != GameStateName.PlayGame)
		{
			return false;
		}
		return !UAP_AccessibilityManager.IsEnabled() || !UAP_AccessibilityManager.IsActive();
	}

	// true = PlayStation gamepad read directly through HID (PortSonyInput); Unity input is ignored for it.
	private static bool s_UseHid;

	private static bool AnyDown(KeyCode[] keys)
	{
		foreach (KeyCode k in keys)
		{
			if (s_UseHid ? PortSonyInput.WasPressed(k - KeyCode.JoystickButton0) : Input.GetKeyDown(k))
			{
				return true;
			}
		}
		return false;
	}

	private static Vector2 Strongest(Vector2 a, Vector2 b)
	{
		return (b.sqrMagnitude > a.sqrMagnitude) ? b : a;
	}

	private void UpdateJoystick()
	{
		DetectControllerType();
		PortSonyInput.Poll();
		s_UseHid = PortSonyInput.Active;
		if (s_UseHid)
		{
			m_Sony = true;
		}
		// Unity: stick Y is positive downwards (PortJoyY is already inverted); d-pad Y is positive upwards.
		Vector2 value = new Vector2(ReadAxis("PortJoyX"), ReadAxis("PortJoyY"));
		if (s_UseHid)
		{
			value = Strongest(Strongest(PortSonyInput.LeftStick, PortSonyInput.RightStick), PortSonyInput.Dpad);
		}
		else if (m_Sony)
		{
			value = Strongest(value, new Vector2(ReadAxis("PortAxis2"), -ReadAxis("PortAxis5")));
			value = Strongest(value, new Vector2(ReadAxis("PortAxis6"), ReadAxis("PortAxis7")));
		}
		else
		{
			value = Strongest(value, new Vector2(ReadAxis("PortAxis3"), -ReadAxis("PortAxis4")));
			value = Strongest(value, new Vector2(ReadAxis("PortAxis5"), ReadAxis("PortAxis6")));
		}
		// Generates a key "press" only when the direction crosses the threshold (no repeat while held)
		if (Mathf.Abs(m_StickLast.x) < c_StickRelease && Mathf.Abs(m_StickLast.y) < c_StickRelease)
		{
			if (Mathf.Abs(value.x) >= c_StickThreshold || Mathf.Abs(value.y) >= c_StickThreshold)
			{
				if (Mathf.Abs(value.x) > Mathf.Abs(value.y))
				{
					if (value.x < 0f)
					{
						s_Left = true;
					}
					else
					{
						s_Right = true;
					}
				}
				else if (value.y > 0f)
				{
					s_Up = true;
				}
				else
				{
					s_Down = true;
				}
				m_StickLast = value;
			}
		}
		else if (Mathf.Abs(value.x) < c_StickRelease && Mathf.Abs(value.y) < c_StickRelease)
		{
			m_StickLast = Vector2.zero;
		}
		Layout layout = m_Sony ? c_Sony : c_Xbox;
		// Xbox triggers are axes: generate a press when they pass the halfway point
		bool leftTrigger = false;
		bool rightTrigger = false;
		if (!m_Sony)
		{
			bool lt = ReadAxis("PortAxis8") > 0.5f;
			bool rt = ReadAxis("PortAxis9") > 0.5f;
			leftTrigger = lt && !m_LeftTriggerDown;
			rightTrigger = rt && !m_RightTriggerDown;
			m_LeftTriggerDown = lt;
			m_RightTriggerDown = rt;
		}
		if (IsRunning())
		{
			// Run: buttons become the game gestures; the d-pad still works (above).
			if (AnyDown(layout.Jump))
			{
				GameSwipeUp = true;
			}
			if (AnyDown(layout.Slide))
			{
				GameSwipeDown = true;
			}
			if (AnyDown(layout.Left) || leftTrigger)
			{
				GameSwipeLeft = true;
			}
			if (AnyDown(layout.Right) || rightTrigger)
			{
				GameSwipeRight = true;
			}
			if (AnyDown(layout.Shoot))
			{
				GameTap = true;
			}
			if (AnyDown(layout.Pause))
			{
				s_PauseToggle = true;
			}
		}
		else if (IsPauseMenu() && AnyDown(layout.Pause))
		{
			// Pause menu: Start/Options (and Share/Back) resume the game, like Esc
			s_Cancel = true;
		}
		else
		{
			if (AnyDown(layout.Submit))
			{
				s_Submit = true;
			}
			if (AnyDown(layout.Cancel))
			{
				s_Cancel = true;
			}
		}
	}

	private void UpdateMouse()
	{
		if (Input.touchCount > 0)
		{
			return;
		}
		if (Input.GetMouseButtonDown(0))
		{
			m_MouseDown = true;
			m_MouseSwiped = false;
			m_MouseStart = Input.mousePosition;
		}
		else if (m_MouseDown && Input.GetMouseButton(0) && !m_MouseSwiped)
		{
			Vector2 diff = (Vector2)Input.mousePosition - m_MouseStart;
			diff = new Vector2(diff.x / (float)Screen.width, diff.y / (float)Screen.width);
			if (diff.magnitude > c_MouseSwipeThreshold)
			{
				if (Mathf.Abs(diff.y) <= Mathf.Abs(diff.x))
				{
					if (diff.x < 0f)
					{
						GameSwipeLeft = true;
					}
					else
					{
						GameSwipeRight = true;
					}
				}
				else if (diff.y < 0f)
				{
					GameSwipeDown = true;
				}
				else
				{
					GameSwipeUp = true;
				}
				m_MouseSwiped = true;
			}
		}
		if (Input.GetMouseButtonUp(0) && m_MouseDown)
		{
			m_MouseDown = false;
			if (!m_MouseSwiped)
			{
				GameTap = true;
			}
		}
	}
}
